# coding=utf-8
product_map = {
    1: 'LIFX Original 1000',
    3: 'LIFX Color 650',
    10: 'LIFX White 800 (Low Voltage)',
    11: 'LIFX White 800 (High Voltage)',
    15: 'LIFX Color 1000',
    18: 'LIFX White 900 BR30 (Low Voltage)',
    19: 'LIFX White 900 BR30 (High Voltage)',
    20: 'LIFX Color 1000 BR30',
    22: 'LIFX Color 1000',
    27: 'LIFX A19',
    28: 'LIFX BR30',
    29: 'LIFX A19 Night Vision',
    30: 'LIFX BR30 Night Vision',
    31: 'LIFX Z',
    32: 'LIFX Z',
    36: 'LIFX Downlight',
    37: 'LIFX Downlight',
    38: 'LIFX Beam',
    39: 'LIFX Downlight White to Warm',
    40: 'LIFX Downlight',
    43: 'LIFX A19',
    44: 'LIFX BR30',
    45: 'LIFX A19 Night Vision',
    46: 'LIFX BR30 Night Vision',
    49: 'LIFX Mini Color',
    50: 'LIFX Mini White to Warm',
    51: 'LIFX Mini White',
    52: 'LIFX GU10',
    53: 'LIFX GU10',
    55: 'LIFX Tile',
    57: 'LIFX Candle',
    59: 'LIFX Mini Color',
    60: 'LIFX Mini White to Warm',
    61: 'LIFX Mini White',
    62: 'LIFX A19',
    63: 'LIFX BR30',
    64: 'LIFX A19 Night Vision',
    65: 'LIFX BR30 Night Vision',
    66: 'LIFX Mini White',
    68: 'LIFX Candle',
    70: 'LIFX Switch',
    71: 'LIFX Switch',
    81: 'LIFX Candle White to Warm',
    82: 'LIFX Filament Clear',
    85: 'LIFX Filament Amber',
    87: 'LIFX Mini White',
    88: 'LIFX Mini White',
    89: 'LIFX Switch',
    90: 'LIFX Clean',
    91: 'LIFX Color',
    92: 'LIFX Color',
    93: 'LIFX A19 US',
    94: 'LIFX BR30',
    96: 'LIFX Candle White to Warm',
    97: 'LIFX A19',
    98: 'LIFX BR30',
    99: 'LIFX Clean',
    100: 'LIFX Filament Clear',
    101: 'LIFX Filament Amber',
    109: 'LIFX A19 Night Vision',
    110: 'LIFX BR30 Night Vision',
    111: 'LIFX A19 Night Vision',
    112: 'LIFX BR30 Night Vision Intl',
    113: 'LIFX Mini WW US',
    114: 'LIFX Mini WW Intl',
    115: 'LIFX Switch',
    116: 'LIFX Switch',
    117: 'LIFX Z US',
    118: 'LIFX Z Intl',
    119: 'LIFX Beam US',
    120: 'LIFX Beam Intl',
    121: 'LIFX Downlight Intl',
    122: 'LIFX Downlight US',
    123: 'LIFX Color US',
    124: 'LIFX Colour Intl',
    125: 'LIFX White to Warm US',
    126: 'LIFX White to Warm Intl',
    127: 'LIFX White US',
    128: 'LIFX White Intl',
    129: 'LIFX Color US',
    130: 'LIFX Colour Intl',
    131: 'LIFX White To Warm US',
    132: 'LIFX White To Warm Intl',
    133: 'LIFX White US',
    134: 'LIFX White Intl',
    135: 'LIFX GU10 Color US',
    136: 'LIFX GU10 Colour Intl',
    137: 'LIFX Candle Color US',
    138: 'LIFX Candle Colour Intl',
    141: 'LIFX Neon US',
    142: 'LIFX Neon Intl',
    143: 'LIFX String US',
    144: 'LIFX String Intl',
    161: 'LIFX Outdoor Neon US',
    162: 'LIFX Outdoor Neon Intl',
    163: 'LIFX A19 US',
    164: 'LIFX BR30 US',
    165: 'LIFX A19 Intl',
    166: 'LIFX BR30 Intl',
    167: 'LIFX Downlight',
    168: 'LIFX Downlight',
    169: 'LIFX A21 1600lm US',
    170: 'LIFX A21 1600lm Intl',
    171: 'LIFX Round Spot US',
    173: 'LIFX Round Path US',
    174: 'LIFX Square Path US',
    175: 'LIFX PAR38 US',
    176: 'LIFX Ceiling US',
    177: 'LIFX Ceiling Intl',
    178: 'LIFX Downlight US',
    179: 'LIFX Downlight US',
    180: 'LIFX Downlight US',
    181: 'LIFX Color US',
    182: 'LIFX Colour Intl',
    185: 'LIFX Candle Color US',
    186: 'LIFX Candle Colour Intl',
    187: 'LIFX Candle Color US',
    188: 'LIFX Candle Colour Intl',
    201: 'LIFX Ceiling 13x26" US',
    202: 'LIFX Ceiling 13x26" Intl',
    203: 'LIFX String US',
    204: 'LIFX String Intl',
    205: 'LIFX Indoor Neon US',
    206: 'LIFX Indoor Neon Intl',
    213: 'LIFX Permanent Outdoor US',
    214: 'LIFX Permanent Outdoor Intl',
    215: 'LIFX Candle Color US',
    216: 'LIFX Candle Colour Intl',
    217: 'LIFX Tube US',
    218: 'LIFX Tube Intl',
    219: 'LIFX Capsule Mini US',
    220: 'LIFX Capsule Mini Intl',
    221: 'LIFX Round Spot Intl',
    222: 'LIFX Round Path Intl',
    223: 'LIFX Downlight US',
    224: 'LIFX Downlight Intl',
    225: 'LIFX PAR38 INTL',
    None: 'Unknown product',
}

# Identifies which products are lights.
light_products = [1, 3, 10, 11, 15, 18, 19, 20, 22, 27, 28, 29, 30, 31, 32, 36, 37, 38, 39, 40, 43, 44, 45, 46, 49,
     50, 51, 52, 53, 55, 57, 59, 60, 61, 62, 63, 64, 65, 66, 68, 81, 82, 85, 87, 88, 90, 91, 92, 93, 94, 96, 97, 98, 99,
     100, 101, 109, 110, 111, 112, 113, 114, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
     130, 131, 132, 133, 134, 135, 136, 137, 138, 141, 142, 143, 144, 161, 162, 163, 164, 165, 166, 167, 168, 169,
     170, 171, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 185, 186, 187, 188, 201, 202, 203, 204, 205, 206, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225]

# Identifies which products are switches.
switch_products = [70, 71, 89, 115, 116]

features_map = {
    1: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Original 1000',
        'relays': False,
        'temperature': False},
    3: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Color 650',
        'relays': False,
        'temperature': False},
    10: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 6500,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX White 800 (Low Voltage)',
        'relays': False,
        'temperature': False},
    11: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 6500,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX White 800 (High Voltage)',
        'relays': False,
        'temperature': False},
    15: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Color 1000',
        'relays': False,
        'temperature': False},
    18: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX White 900 BR30 (Low Voltage)',
        'relays': False,
        'temperature': False},
    19: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX White 900 BR30 (High Voltage)',
        'relays': False,
        'temperature': False},
    20: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Color 1000 BR30',
        'relays': False,
        'temperature': False},
    22: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Color 1000',
        'relays': False,
        'temperature': False},
    27: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX A19',
        'relays': False,
        'temperature': False},
    28: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX BR30',
        'relays': False,
        'temperature': False},
    29: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX A19 Night Vision',
        'relays': False,
        'temperature': False},
    30: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX BR30 Night Vision',
        'relays': False,
        'temperature': False},
    31: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': True,
        'name': 'LIFX Z',
        'relays': False,
        'temperature': False},
    32: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': True,
        'name': 'LIFX Z',
        'relays': False,
        'temperature': False},
    36: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Downlight',
        'relays': False,
        'temperature': False},
    37: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Downlight',
        'relays': False,
        'temperature': False},
    38: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': True,
        'name': 'LIFX Beam',
        'relays': False,
        'temperature': False},
    39: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Downlight White to Warm',
        'relays': False,
        'temperature': False},
    40: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Downlight',
        'relays': False,
        'temperature': False},
    43: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX A19',
        'relays': False,
        'temperature': False},
    44: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX BR30',
        'relays': False,
        'temperature': False},
    45: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX A19 Night Vision',
        'relays': False,
        'temperature': False},
    46: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX BR30 Night Vision',
        'relays': False,
        'temperature': False},
    49: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Mini Color',
        'relays': False,
        'temperature': False},
    50: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 6500,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Mini White to Warm',
        'relays': False,
        'temperature': False},
    51: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2700,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX Mini White',
        'relays': False,
        'temperature': False},
    52: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX GU10',
        'relays': False,
        'temperature': False},
    53: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX GU10',
        'relays': False,
        'temperature': False},
    55: {       'buttons': False,
        'chain': True,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 2500,
        'multizone': False,
        'name': 'LIFX Tile',
        'relays': False,
        'temperature': False},
    57: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle',
        'relays': False,
        'temperature': False},
    59: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Mini Color',
        'relays': False,
        'temperature': False},
    60: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 6500,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Mini White to Warm',
        'relays': False,
        'temperature': False},
    61: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2700,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX Mini White',
        'relays': False,
        'temperature': False},
    62: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A19',
        'relays': False,
        'temperature': False},
    63: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX BR30',
        'relays': False,
        'temperature': False},
    64: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A19 Night Vision',
        'relays': False,
        'temperature': False},
    65: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX BR30 Night Vision',
        'relays': False,
        'temperature': False},
    66: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2700,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX Mini White',
        'relays': False,
        'temperature': False},
    68: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle',
        'relays': False,
        'temperature': False},
    70: {       'buttons': True,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': None,
        'min_kelvin': None,
        'multizone': False,
        'name': 'LIFX Switch',
        'relays': True,
        'temperature': False},
    71: {       'buttons': True,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': None,
        'min_kelvin': None,
        'multizone': False,
        'name': 'LIFX Switch',
        'relays': True,
        'temperature': False},
    81: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 6500,
        'min_kelvin': 2200,
        'multizone': False,
        'name': 'LIFX Candle White to Warm',
        'relays': False,
        'temperature': False},
    82: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2100,
        'min_kelvin': 2100,
        'multizone': False,
        'name': 'LIFX Filament Clear',
        'relays': False,
        'temperature': False},
    85: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2000,
        'min_kelvin': 2000,
        'multizone': False,
        'name': 'LIFX Filament Amber',
        'relays': False,
        'temperature': False},
    87: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2700,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX Mini White',
        'relays': False,
        'temperature': False},
    88: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2700,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX Mini White',
        'relays': False,
        'temperature': False},
    89: {       'buttons': True,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': None,
        'min_kelvin': None,
        'multizone': False,
        'name': 'LIFX Switch',
        'relays': True,
        'temperature': False},
    90: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': True,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Clean',
        'relays': False,
        'temperature': False},
    91: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Color',
        'relays': False,
        'temperature': False},
    92: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Color',
        'relays': False,
        'temperature': False},
    93: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A19 US',
        'relays': False,
        'temperature': False},
    94: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX BR30',
        'relays': False,
        'temperature': False},
    96: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 6500,
        'min_kelvin': 2200,
        'multizone': False,
        'name': 'LIFX Candle White to Warm',
        'relays': False,
        'temperature': False},
    97: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A19',
        'relays': False,
        'temperature': False},
    98: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX BR30',
        'relays': False,
        'temperature': False},
    99: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': True,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Clean',
        'relays': False,
        'temperature': False},
    100: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2100,
        'min_kelvin': 2100,
        'multizone': False,
        'name': 'LIFX Filament Clear',
        'relays': False,
        'temperature': False},
    101: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2000,
        'min_kelvin': 2000,
        'multizone': False,
        'name': 'LIFX Filament Amber',
        'relays': False,
        'temperature': False},
    109: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A19 Night Vision',
        'relays': False,
        'temperature': False},
    110: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX BR30 Night Vision',
        'relays': False,
        'temperature': False},
    111: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A19 Night Vision',
        'relays': False,
        'temperature': False},
    112: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': True,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX BR30 Night Vision Intl',
        'relays': False,
        'temperature': False},
    113: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Mini WW US',
        'relays': False,
        'temperature': False},
    114: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Mini WW Intl',
        'relays': False,
        'temperature': False},
    115: {       'buttons': True,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': None,
        'min_kelvin': None,
        'multizone': False,
        'name': 'LIFX Switch',
        'relays': True,
        'temperature': False},
    116: {       'buttons': True,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': None,
        'min_kelvin': None,
        'multizone': False,
        'name': 'LIFX Switch',
        'relays': True,
        'temperature': False},
    117: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Z US',
        'relays': False,
        'temperature': False},
    118: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Z Intl',
        'relays': False,
        'temperature': False},
    119: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Beam US',
        'relays': False,
        'temperature': False},
    120: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Beam Intl',
        'relays': False,
        'temperature': False},
    121: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Downlight Intl',
        'relays': False,
        'temperature': False},
    122: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Downlight US',
        'relays': False,
        'temperature': False},
    123: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Color US',
        'relays': False,
        'temperature': False},
    124: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Colour Intl',
        'relays': False,
        'temperature': False},
    125: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX White to Warm US',
        'relays': False,
        'temperature': False},
    126: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX White to Warm Intl',
        'relays': False,
        'temperature': False},
    127: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2700,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX White US',
        'relays': False,
        'temperature': False},
    128: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2700,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX White Intl',
        'relays': False,
        'temperature': False},
    129: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Color US',
        'relays': False,
        'temperature': False},
    130: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Colour Intl',
        'relays': False,
        'temperature': False},
    131: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX White To Warm US',
        'relays': False,
        'temperature': False},
    132: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX White To Warm Intl',
        'relays': False,
        'temperature': False},
    133: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2700,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX White US',
        'relays': False,
        'temperature': False},
    134: {       'buttons': False,
        'chain': False,
        'color': False,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 2700,
        'min_kelvin': 2700,
        'multizone': False,
        'name': 'LIFX White Intl',
        'relays': False,
        'temperature': False},
    135: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX GU10 Color US',
        'relays': False,
        'temperature': False},
    136: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX GU10 Colour Intl',
        'relays': False,
        'temperature': False},
    137: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle Color US',
        'relays': False,
        'temperature': False},
    138: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle Colour Intl',
        'relays': False,
        'temperature': False},
    141: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Neon US',
        'relays': False,
        'temperature': False},
    142: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Neon Intl',
        'relays': False,
        'temperature': False},
    143: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX String US',
        'relays': False,
        'temperature': False},
    144: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX String Intl',
        'relays': False,
        'temperature': False},
    161: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Outdoor Neon US',
        'relays': False,
        'temperature': False},
    162: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Outdoor Neon Intl',
        'relays': False,
        'temperature': False},
    163: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A19 US',
        'relays': False,
        'temperature': False},
    164: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX BR30 US',
        'relays': False,
        'temperature': False},
    165: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A19 Intl',
        'relays': False,
        'temperature': False},
    166: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX BR30 Intl',
        'relays': False,
        'temperature': False},
    167: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Downlight',
        'relays': False,
        'temperature': False},
    168: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Downlight',
        'relays': False,
        'temperature': False},
    169: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A21 1600lm US',
        'relays': False,
        'temperature': False},
    170: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX A21 1600lm Intl',
        'relays': False,
        'temperature': False},
    171: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Round Spot US',
        'relays': False,
        'temperature': False},
    173: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Round Path US',
        'relays': False,
        'temperature': False},
    174: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Square Path US',
        'relays': False,
        'temperature': False},
    175: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX PAR38 US',
        'relays': False,
        'temperature': False},
    176: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Ceiling US',
        'relays': False,
        'temperature': False},
    177: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Ceiling Intl',
        'relays': False,
        'temperature': False},
    178: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Downlight US',
        'relays': False,
        'temperature': False},
    179: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Downlight US',
        'relays': False,
        'temperature': False},
    180: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Downlight US',
        'relays': False,
        'temperature': False},
    181: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Color US',
        'relays': False,
        'temperature': False},
    182: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Colour Intl',
        'relays': False,
        'temperature': False},
    185: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle Color US',
        'relays': False,
        'temperature': False},
    186: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle Colour Intl',
        'relays': False,
        'temperature': False},
    187: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle Color US',
        'relays': False,
        'temperature': False},
    188: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle Colour Intl',
        'relays': False,
        'temperature': False},
    201: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Ceiling 13x26" US',
        'relays': False,
        'temperature': False},
    202: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Ceiling 13x26" Intl',
        'relays': False,
        'temperature': False},
    203: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX String US',
        'relays': False,
        'temperature': False},
    204: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX String Intl',
        'relays': False,
        'temperature': False},
    205: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Indoor Neon US',
        'relays': False,
        'temperature': False},
    206: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Indoor Neon Intl',
        'relays': False,
        'temperature': False},
    213: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Permanent Outdoor US',
        'relays': False,
        'temperature': False},
    214: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': True,
        'name': 'LIFX Permanent Outdoor Intl',
        'relays': False,
        'temperature': False},
    215: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle Color US',
        'relays': False,
        'temperature': False},
    216: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Candle Colour Intl',
        'relays': False,
        'temperature': False},
    217: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Tube US',
        'relays': False,
        'temperature': False},
    218: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Tube Intl',
        'relays': False,
        'temperature': False},
    219: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Capsule Mini US',
        'relays': False,
        'temperature': False},
    220: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Capsule Mini Intl',
        'relays': False,
        'temperature': False},
    221: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Round Spot Intl',
        'relays': False,
        'temperature': False},
    222: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': True,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Round Path Intl',
        'relays': False,
        'temperature': False},
    223: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Downlight US',
        'relays': False,
        'temperature': False},
    224: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX Downlight Intl',
        'relays': False,
        'temperature': False},
    225: {       'buttons': False,
        'chain': False,
        'color': True,
        'hev': False,
        'infrared': False,
        'matrix': False,
        'max_kelvin': 9000,
        'min_kelvin': 1500,
        'multizone': False,
        'name': 'LIFX PAR38 INTL',
        'relays': False,
        'temperature': False},
}
